name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Instalar lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
      - name: Remover diretório remoto (se existir)
        run: |
          echo "Tentando remover diretório remoto: ${{ secrets.FTP_DIRECTORY }}"
          lftp -u "${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }}" ftp://${{ secrets.FTP_HOST }} -e "
            set net:use-ipv6 false;
            cls -1 ${{ secrets.FTP_DIRECTORY }} && rm -r ${{ secrets.FTP_DIRECTORY }};
            quit
          "
      - name: Criar diretório remoto no FTP
        run: |
          echo "Criando diretório remoto: ${{ secrets.FTP_DIRECTORY }}"
          lftp -u "${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }}" ftp://${{ secrets.FTP_HOST }} -e "
            set net:use-ipv6 false;
            mkdir -p ${{ secrets.FTP_DIRECTORY }};
            quit
          "
      - name: Transferir via FTP com lftp
        run: |
          echo "Enviando e renomeando arquivo para o diretório remoto: ${{ secrets.FTP_DIRECTORY }}"
          lftp -u "${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }}" ftp://${{ secrets.FTP_HOST }} -e "
            set net:use-ipv6 false;
            cd ${{ secrets.FTP_DIRECTORY }};
            put waranasLibrary_03-25.php;
            mv waranasLibrary_03-25.php waranas.php;
            quit
          "
